
TP noté de Calcul scientifique
 =====
 
1 - Consignes 
-----

L'examen sera à réaliser en python 3. Les questions du sujet doivent être résolues uniquement avec des fonctions des librairies `numpy`, `scipy` et `matplotlib` vu durant l'année.
	
**<span style="color:red"> À part si cela est précisé, vous ne devez pas utiliser directement de boucle (`for`,`while`) ou de branchement conditionnel (`if`).</span>.**

**<span style="color:red"> 
Vous rendrez ce notebook en fin d'examen sur la plateforme ecampus sans en changer le nom. Les réponses sont à mettre dans le présent notebook et non dans un autre fichier.</span>**

**<span style="color:red"> 
Aucun envoi par mail ou soumission en retard ne sera accepté.</span>**

**<span style="color:red"> 
Vous devez avant tous avoir un code fonctionnel, ne perdez pas de temps sur des considérations esthétiques et supprimez les codes non fonctionnels.</span>**

**<span style="color:red"> 
Vous ne devez pas créer de nouveau bloque et vous répondrez aux questions uniquement dans les zones prévues.</span>**

Gestion du temps:
* Vous avez 2h30 pour traiter 25 questions, soit une moyenne de 6mn par question.
* Il y a des questions faciles auquelles vous repondrez en moins de 5mn.
* Vous pouvez toujours laisser une question en suspens pour y revenir après.
* Ne restez jamais bloquez plus de 10 mn sur une même question, allez à la question suivante.
* Le sujet n'est pas ordonné par difficulté. Des questions plus difficiles peuvent se trouver en début de sujet et des questions plus simple après.
    

2 - Sujet
-----    
    


In [3]:
import numpy as np

import scipy as sc
import scipy.optimize
import scipy.spatial
import scipy.signal

import matplotlib.pyplot as plt

In [3]:
# À compléter
id_etu = {
    "Nom": "ANTOINE",
    "Prénom": "Evens",
    "Numéro d'étudiant": "22209813",
    "Groupe": "2A"
}    


In [4]:

# Ce bloc permet de valider votre code. Vous ne devez pas le modifier.  
try:
    assert len(id_etu['Nom'])>1,'Nom invalide'
    assert len(id_etu['Prénom'])>1,'Prénom invalide'
    assert any(chr.isdigit() for chr in id_etu["Numéro d'étudiant"]),"Numéro d'étudiant invalide"
    assert id_etu['Groupe'] in [str(i)+g for i in range(1,5) for g in 'AB' ],'Groupe invalide'
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    #raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.'))     
    

 Ok - Tous les tests sont validés.


Zone de commentaires:

---

Question 1: Écrivez une fonction qui retourne les 9 plus petits éléments d'un vecteur `v` trié du plus petit au plus grand.

<span style="color:teal">Exemple :</span> <br>

Les 9 plus petits éléments de `[71 62 83 35 78 48 78 14 32 87  1  3]` sont `[ 1  3 14 32 35 48 62 71 78]`
    

In [7]:

def fct(v):
    # YOUR CODE HERE
    v=np.sort(v)
    m=v[0:9]
    return m

v=np.array([71, 62 ,83 ,35 ,78, 48, 78, 14, 32, 87,  1,  3])
fct(v)

array([ 1,  3, 14, 32, 35, 48, 62, 71, 78])

In [8]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([71, 62, 83, 35, 78, 48, 78, 14, 32, 87,  1,  3])
    res = fct(v)
    np.testing.assert_equal(len(res),9,'Taille du vecteur incorrect.')
    np.testing.assert_equal(res,np.array([ 1,  3, 14, 32, 35, 48, 62, 71, 78]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 2: 
Écrivez une fonction prenant en entrée un vecteur et retournant un tableau de tous les éléments qui sont strictement inférieurs à 5.

<span style="color:teal">Exemple :</span> <br>
`[6 6 4 4 2 0 2]` a pour sortie `[4 4 2 0 2]`
    

In [9]:

def fct(v):
    v=v[v<5]
    return v


In [10]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    
    v = np.array([6,6,4,4,2,0,2])
    np.testing.assert_equal(fct(v),np.array([4,4,2,0,2]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 3:  À partir de 2 vecteurs v1 et v2, construisez à l'aide du broadcasting la matrice des multiplications entre les valeurs des deux vecteurs. 
Par exemple pour les vecteurs `[30 40 50]`  et  `[1 2 3 4 5]` la matrice retournée est la suivante :

```
[[ 30  60  90 120 150]
 [ 40  80 120 160 200]
 [ 50 100 150 200 250]]
```

    

In [13]:

def fct(v1,v2):
    v1=v1.reshape((-1,1))
    v2=v2.reshape((-1,5))
    v=v1*v2
    return v


In [14]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    v1 = np.array([30, 40, 50])
    v2 = np.array([1, 2, 3, 4, 5])
    res = fct(v1,v2)
    np.testing.assert_equal(list(res.shape),(len(v1),len(v2)),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[ 30,  60,  90, 120, 150],
           [ 40,  80, 120, 160, 200],
           [ 50, 100, 150, 200, 250]]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 4: 
Définir une fonction retournant un tableau `Y` contenant les 46 plus grandes valeurs du tableau x passé en argument triées par ordre décroissant.


In [15]:

def f(x):
    Y=x[-46:]
    return Y


In [16]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = np.cos(np.arange(500)/14) * np.sin(np.arange(500)/54)
    Y = f(x)
    
    np.testing.assert_equal(Y.shape,(46,))
    np.testing.assert_equal(Y.max() < 1, True)
    np.testing.assert_equal(Y.min() > -1, True)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 5: Étant donnée une matrice `M`, écrivez une fonction retournant tous les indices de(s) colonne(s) de `M` contenant la valeur minimale .
    
<span style="color:teal">Exemple :</span> <br>
Pour la matrice:
```
[[13 32 24  4 23]
 [19 29 16 18 16]
 [14  3 10 31 37]
 [38 26 10 19 27]
 [20 12  9 35  5]
 [31 35 35  7 11]
 [22 38 27 14  8]
 [31 21 15 34 19]]
```

la valeur minimale (ici 3) se trouve aux colonne d'indices: `[1]`.
    

In [17]:

def fct(M):
    M=np.argwhere(M==np.min(M))
    return M[:,1]


In [18]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[13, 32, 24,  4, 23],
           [19, 29, 16, 18, 16],
           [14,  3, 10, 31, 37],
           [38, 26, 10, 19, 27],
           [20, 12,  9, 35,  5],
           [31, 35, 35,  7, 11],
           [22, 38, 27, 14,  8],
           [31, 21, 15, 34, 19]])
    res = fct(M)
    np.testing.assert_equal(len(res),1,'Nombre de sortie incorrecte.')
    np.testing.assert_equal(res,np.array([1]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 6: 
Écrivez une fonction qui retourne la matrice construite en suivant les étapes suivantes:
- Construire le vecteur `v` constitué des entiers de 13 à 29 (exclu).
- Transformer `v` en la matrice suivante (en deux/trois instructions au plus).

```
[[28 24 20 16]
 [27 23 19 15]
 [26 22 18 14]
 [25 21 17 13]]
```
    

In [26]:

def fct():
    v=np.arange(13,29)
    v=v.reshape(4,4)
    v=v[::-1]
    v=np.transpose(v)
    v=v[::-1]
    return v
fct()


array([[28, 24, 20, 16],
       [27, 23, 19, 15],
       [26, 22, 18, 14],
       [25, 21, 17, 13]])

In [27]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    res = fct()
    np.testing.assert_equal(list(res.shape),(4, 4),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[28, 24, 20, 16],
           [27, 23, 19, 15],
           [26, 22, 18, 14],
           [25, 21, 17, 13]]),'Résultat incorrecte.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 7: 
Ecrire une fonction `mesure` qui retourne la norme euclidienne d'un vecteur de taille quelconque.


In [28]:

def mesure(x):
    return np.linalg.norm(x)

In [29]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    
    x = np.arange(2)
    d1 = mesure(x)
    
    np.testing.assert_equal(d1,1.0)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 8: 

Étant donné un vecteur `v`, écrivez une fonction qui remplace tous les éléments de `v` qui sont inférieurs à 8 par -1, et tous les éléments qui sont supérieurs à 14 par 2.

<span style="color:teal">Exemple :</span> <br>
`[ 8  6 14 17 12  4  2]`

a pour sortie:

`[ 8 -1 14  2 12 -1 -1]`
    

In [30]:

def fct(v):
    # YOUR CODE HERE
    v[v<8],v[v>14] = -1,2
    return v


In [31]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([ 8,  6, 14, 17, 12,  4,  2])
    res = fct(v)
    np.testing.assert_equal(res,np.array([ 8, -1, 14,  2, 12, -1, -1]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 9: 
Créer un tableau numpy `x` contenant la liste des carrés des entiers allant de 4 à 13 (inclus).


In [32]:

def liste_carres():
    x=np.arange(4,14)
    x=x**2
    return x

In [33]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = liste_carres()
    np.testing.assert_equal(x.min(),4**2)
    np.testing.assert_equal(x.max(),13**2)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 10: Écrivez une fonction inversant l'ordre des éléments des colonnes d'indice pair d'une matrice `M`.
           
<span style='color:teal'> Exemple</span> <br>
En partant de la matrice:
```
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]
```


Le résultat attendu est:
```
[[25  2 27  4 29  6]
 [19  8 21 10 23 12]
 [13 14 15 16 17 18]
 [ 7 20  9 22 11 24]
 [ 1 26  3 28  5 30]]
```
    

In [ ]:

def fct(M):
    


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[ 1,  2,  3,  4,  5,  6],
           [ 7,  8,  9, 10, 11, 12],
           [13, 14, 15, 16, 17, 18],
           [19, 20, 21, 22, 23, 24],
           [25, 26, 27, 28, 29, 30]])
    res = fct(M)
    np.testing.assert_equal(res.shape,(5, 6),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[25,  2, 27,  4, 29,  6],
           [19,  8, 21, 10, 23, 12],
           [13, 14, 15, 16, 17, 18],
           [ 7, 20,  9, 22, 11, 24],
           [ 1, 26,  3, 28,  5, 30]]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 11: 
Créer une fonction `superieur` qui prend en entrée un tableau numpy et renvois 
un tableau de booléens de même taille que le tableau d'entrée contenant `True`
 si les valeurs du tableau d'entrée sont superieur (strictement) à -0.2095, `False` sinon.


In [ ]:

def superieur(x):
    # YOUR CODE HERE
    raise NotImplementedError()


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = np.random.randn(50)
    
    np.testing.assert_equal(x.shape,superieur(x).shape)
    np.testing.assert_equal(superieur(x).dtype, np.dtype('bool'))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 12: 
Écrire une fonction `diagMatrice` qui construit et retourne une matrice carrée de taille $(12,12)$ dont les éléments sont de valeur $1$ exceptés ceux sur la $3$-ème diagonale (bas gauche -> haut droite) qui sont tous à $0$.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```


In [97]:

def diagMatrice():
    # YOUR CODE HERE
    res = np.zeros([12,12])+1
    v = res[:10,2::-1]
    np.fill_diagonal(v,0)
    return res


In [98]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = diagMatrice()
    np.testing.assert_equal(mat.shape,(12,12))
    np.testing.assert_almost_equal(np.sum(mat),141)
    np.testing.assert_almost_equal(np.diag(mat[:3,2::-1]),0)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 13: 
Étant donné un vecteur `u` de taille 5, construisez une fonction retourrnant un vecteur de taille $25 = 5\times5$
où chaque élément de `u` est répété consécutivement 5 fois.

<span style="color:teal">Exemple :</span> <br>
À partir du vecteur:

```
[ 6  4 13 10 12]
```

on obtient:

```
[ 6  6  6  6  6  4  4  4  4  4 13 13 13 13 13 10 10 10 10 10 12 12 12 12
 12]
```
           

In [ ]:

def fct(v):
    # YOUR CODE HERE
    raise NotImplementedError()
    


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([ 6,  4, 13, 10, 12])
    res = fct(v)
    np.testing.assert_equal(np.sum(res),np.sum(v)*5,'Exemple incorrect.')
    np.testing.assert_equal(res,np.array([ 6,  6,  6,  6,  6,  4,  4,  4,  4,  4, 13, 13, 13, 13, 13, 10, 10,
           10, 10, 10, 12, 12, 12, 12, 12]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 14: 
Créez une matrice `mat` de taille (4,4) dont toutes les valeurs sont à 6 sauf la case (0,2) qui vaut 0.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[6. 6. 0. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
```


In [113]:

# YOUR CODE HERE
mat = np.arange((4,4))
mat[0:2] = 0
print(mat)


TypeError: arange: scalar arguments expected instead of a tuple.

In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    np.testing.assert_equal(mat.shape,(4,4),err_msg='Attention à la taille')
    np.testing.assert_almost_equal(np.sum(mat),6*(4*4-1))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 15: 

Écrivez une fonction permettant de concaténer les tableaux `x` et `y` de taille [2 7] et [1 7] selon l'axe des ligne. 
 
<span style="color:teal">Exemple :</span> <br>
Sur les entrées 
```
[[8 8 6 0 0 2 8]
 [4 7 7 5 8 1 7]]
```
et
```
[[3 6 5 5 1 3 8]]
```

le résultat attendu est 

```
[[8 8 6 0 0 2 8]
 [4 7 7 5 8 1 7]
 [3 6 5 5 1 3 8]]
```


In [ ]:

def fct(x,y):
    # YOUR CODE HERE
    raise NotImplementedError()
    


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    x = np.random.random([2,7])
    y = np.random.random([1,7])
    res = fct(x,y)
    np.testing.assert_equal(res.shape,(3, 7),'Taille du tableau de sortie incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 16: 
Écrire une fonction qui prend en entrée un vecteur dont la longueur est un multiple de 3,
et qui retourne le maximum de chaque séquence de 3 éléments consécutifs.

<span style="color:teal">Exemple :</span> <br>
`[ 5  3  1  8  6 11 12  8  3  5  1  0  0  5  2 12 13  5  0  6 11 10  6 14
  0 14 12  6  7 13]`

a pour sortie

`[ 5 11 12  5  5 13 11 14 14 13]`


In [ ]:

def consecutif(vecteur):
    # YOUR CODE HERE
    raise NotImplementedError()


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    vv = np.random.randint(1,15,8*3)
    res = consecutif(vv)
    np.testing.assert_equal(len(vv),3*len(res))
    np.testing.assert_equal(res[2:],consecutif(vv[(2*3):]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 17: 
Écrivez une fonction prenant une matrice `M` et déterminant dans quelles lignes de `M` se trouve la valeur `6`.
    
<span style="color:teal">Exemple :</span> <br>
Pour la matrice:

```
[[4 5 4 5]
 [6 6 8 3]
 [4 4 9 6]
 [3 8 6 3]
 [9 6 3 6]]
```



la valeur `6` se trouve dans les lignes suivantes:

`[1 2 3 4]`
    

In [ ]:

def fct(M):
    # YOUR CODE HERE
    raise NotImplementedError()


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[4, 5, 4, 5],
           [6, 6, 8, 3],
           [4, 4, 9, 6],
           [3, 8, 6, 3],
           [9, 6, 3, 6]])
    res = fct(M)
    np.testing.assert_equal(len(res),4,'Taille du vecteur incorrect.')
    np.testing.assert_equal(res,np.array([1, 2, 3, 4]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 18: Définir un vecteur aléatoire `alea` de taille $24$ et dont les éléments sont des entiers compris entre $1$ et $17$.

<span style='color:teal'> Exemple</span> <br>
`[ 7 13 16  6  2 14 14 11 14  4 10 16 11 13  5  2  9  3 13 10 16  1  8  3]`

In [74]:


def alea_int():
   # YOUR CODE HERE
   alea = np.random.randint(1,17,24)
   return alea



In [73]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
   
    alea = alea_int()
    np.testing.assert_equal(alea.size,24)
    np.testing.assert_equal(alea>=1,True)
    np.testing.assert_equal(alea<=17,True)
    
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 19: 

Étant donné un vecteur, écrivez une fonction qui détermine si ce vecteur est strictement décroissant ou non. Pour cette question, vous pouvez utiliser une convolution pour calculer la soustraction entre valeur consécutive et en déduire le résultat attendu.
 
<span style="color:teal">Exemple :</span> <br>
Sur l'entrée `[37 31 26 21 14 14 12 12  7]` est renvoyé False



In [ ]:

def fct(v):
    # YOUR CODE HERE
    raise NotImplementedError()
    


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([37, 31, 26, 21, 14, 14, 12, 12,  7])
    res = fct(v)
    np.testing.assert_equal(res,False,'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 20: 
Écrivez une fonction `suppresseColonne` qui prend en entrée une matrice et qui supprime de cette matrice toutes les colonnes qui contiennent la valeur 17

<span style="color:teal">Exemple :</span> <br>
```
[[ 0 18 16 11 21  9 23]
 [ 2 12 14 24  3 11 -2]
 [ 1 21 23 17 22 17 12]]
```
<br>

a pour sortie:

```
[[ 0 18 16 21 23]
 [ 2 12 14  3 -2]
 [ 1 21 23 22 12]]
```


In [65]:

def suppresseColonne(matrice):
    # YOUR CODE HERE
    matrice = np.delete(matrice, 5, axis=1)
    return(matrice)
    

In [66]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = np.arange(24)
    mat[np.random.randint(24)] = 17
    mat[np.random.randint(24)] = 17
    mat = mat.reshape((4,-1))
    res = suppresseColonne(mat)
    np.testing.assert_equal(mat.shape[0],res.shape[0])
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 21: 
Écrivez une fonction qui prend en entrée une matrice, et qui retourne la sous-matrice de taille $(5,5)$ qui forme le coin en bas à gauche de la matrice.

<span style="color:teal"> Exemple</span> <br>
Pour une matrice:
```
[[1 2 2 3 2 4 2 1 2 4 6 5 4 6 4 3 2 1 1 1]
 [1 6 1 1 5 4 6 1 3 3 2 5 5 3 2 6 2 4 1 3]
 [6 1 5 4 6 2 3 3 3 4 2 6 6 6 5 4 4 1 4 3]
 [5 6 2 2 2 3 5 6 2 4 3 1 1 3 6 1 6 6 4 6]
 [4 4 2 6 6 1 3 1 4 4 4 6 5 4 1 6 4 3 5 4]
 [5 5 4 1 2 6 3 1 3 4 4 1 3 4 3 4 4 5 4 6]
 [3 4 2 5 6 1 6 6 6 4 1 1 1 2 1 5 3 1 5 6]
 [2 3 1 1 6 1 2 3 5 2 3 5 3 6 2 6 5 5 6 5]
 [1 6 3 5 5 3 3 1 5 2 3 1 4 3 1 3 2 6 4 6]
 [4 3 1 4 3 6 6 4 1 3 4 5 4 1 1 5 5 1 1 5]
 [3 2 6 3 5 2 3 1 5 2 2 4 5 2 6 4 5 3 1 4]
 [6 3 2 4 4 4 2 6 3 5 6 3 2 2 1 1 3 2 5 3]
 [6 5 6 1 6 6 4 2 3 4 5 6 2 1 3 5 5 4 1 1]
 [3 3 2 6 1 6 3 2 1 4 3 3 1 1 5 2 2 6 4 4]
 [4 4 4 6 6 2 1 1 4 1 6 2 6 4 2 5 5 2 6 2]
 [6 1 2 3 4 1 6 6 1 6 3 2 6 4 2 5 4 3 2 3]
 [6 3 3 2 1 1 1 6 3 3 3 6 1 1 3 6 1 2 1 3]
 [5 6 1 3 4 2 6 1 2 1 3 3 1 3 1 4 5 6 4 3]
 [3 3 2 3 1 2 4 3 6 6 1 1 4 5 3 1 4 3 6 2]
 [6 2 3 2 2 3 1 1 3 3 4 5 3 3 5 3 2 6 4 1]]
```
<br>

le coin en bas à gauche est :
```
[[6 1 2 3 4]
 [6 3 3 2 1]
 [5 6 1 3 4]
 [3 3 2 3 1]
 [6 2 3 2 2]]
```


In [107]:
 
def extraire(matrice):
    # YOUR CODE HERE
    matrice = matrice[0:5, matrice.shape[0]-5:]
    return matrice



In [108]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    matrice = np.random.randint(1,7,size=(20,20))
    res = extraire(matrice)
    np.testing.assert_equal(res.shape,(5,5))
    if 0==0:
        np.testing.assert_equal(res[-1,0],matrice[-1,0])
    elif 0==1:
        np.testing.assert_equal(res[-1,-1],matrice[-1,-1])
    else:
        np.testing.assert_equal(res[0,-1],matrice[0,-1])
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 KO - Au moins un test n'est pas validé
Information sur le test non valide:

Items are not equal:
 ACTUAL: 3
 DESIRED: 4


AssertionError: 
Items are not equal:
 ACTUAL: 3
 DESIRED: 4

Question 22: 
Créez une matrice `mat` de taille (6,3) dont toutes les valeurs sont à 4 sauf la colonne 0 dont les éléments sont tous 0.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[0. 4. 4.]
 [0. 4. 4.]
 [0. 4. 4.]
 [0. 4. 4.]
 [0. 4. 4.]
 [0. 4. 4.]]
```


In [44]:

# YOUR CODE HERE
mat = np.array((6,3))
mat = (mat[:0][:4]) 
print(mat)


[]


In [45]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    np.testing.assert_equal(mat.shape,(6,3),err_msg='Attention à la taille')
    np.testing.assert_almost_equal(np.sum(mat),4*6*(3-1))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 KO - Au moins un test n'est pas validé
Information sur le test non valide:

Items are not equal: Attention à la taille
 ACTUAL: 1
 DESIRED: 2


AssertionError: 
Items are not equal: Attention à la taille
 ACTUAL: 1
 DESIRED: 2

Question 23: 
Écrivez une fonction qui prend en entrée une matrice et qui calcule le produit des éléments des colonnes de $4$ à $6$ (la colonne $6$ étant exclue). 

<span style="color:teal">Exemple :</span> <br>
```
[[4 2 6 2 6 1 3]
 [6 6 2 6 6 3 3]
 [4 2 4 5 1 2 2]
 [1 3 5 2 2 5 3]
 [5 6 5 4 5 1 1]]
```
<br>

a pour sortie `10800`.


In [ ]:

def amalgame(matrice):
    # YOUR CODE HERE
    raise NotImplementedError()



In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
 
    res = amalgame(np.array([[4, 2, 6, 2, 6, 1, 3], [6, 6, 2, 6, 6, 3, 3], [4, 2, 4, 5, 1, 2, 2], [1, 3, 5, 2, 2, 5, 3], [5, 6, 5, 4, 5, 1, 1]]))
    np.testing.assert_almost_equal(res,10800)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 24: 
En utilisant le mécanisme de broadcasting, écrire une fonction `distance_minkowski_matrix` prenant en entrée une matrice
`P` de $n$ lignes (points) et $k$ colonnes (coordonnées) et qui renvois la matrice `D` de taille $n \times n$ tel que $D_{i,j} = \left(\sum_{c=1}^k \left(P_{i,c}-P_{j,c}\right)^2\right)^\frac{1}{2}$ .


In [ ]:

def distance_minkowski_matrix(P):
    # YOUR CODE HERE
    raise NotImplementedError()


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    a = np.random.randint(0,10,(10,2))*2-1
    b = distance_minkowski_matrix(a)
    
    np.testing.assert_equal(b.shape,(10,10),err_msg='Dimensions non valident.')
    np.testing.assert_almost_equal((b < 0.0).sum(), 0,err_msg='Les valeurs calculés sont fausses.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


Question 25: 
Écrire une fonction qui prend en entrée une matrice de taille $(5,4)$ et qui soustrait la ligne $4$ à toutes les lignes de la matrice.

<span style="color:teal">Exemple :</span> <br>
```
[[2 3 1 3]
 [4 2 2 5]
 [6 3 5 2]
 [3 4 5 6]
 [1 4 6 2]]
```
<br>

a pour sortie

```
[[ 1 -1 -5  1]
 [ 3 -2 -4  3]
 [ 5 -1 -1  0]
 [ 2  0 -1  4]
 [ 0  0  0  0]]
```


In [ ]:

def soustrait(matrice):
    # YOUR CODE HERE
    raise NotImplementedError()


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = np.arange(5*4).reshape(-1,4)
    res = soustrait(mat)
    np.testing.assert_equal(res.shape,mat.shape)
    np.testing.assert_almost_equal(np.sum(res),np.sum(mat)-5*np.sum(mat[4]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 
