
TP noté de Calcul scientifique
 =====
 
1 - Consignes 
-----

L'examen sera à réaliser en python 3. Les questions du sujet doivent être résolues uniquement avec des fonctions des librairies `numpy`, `scipy` et `matplotlib` vu durant l'année.
	
**<span style="color:red"> À part si cela est précisé, vous ne devez pas utiliser directement de boucle (`for`,`while`) ou de branchement conditionnel (`if`).</span>.**

**<span style="color:red"> 
Vous rendrez ce notebook en fin d'examen sur la plateforme ecampus sans en changer le nom. Les réponses sont à mettre dans le présent notebook et non dans un autre fichier.</span>**

**<span style="color:red"> 
Aucun envoi par mail ou soumission en retard ne sera accepté.</span>**

**<span style="color:red"> 
Vous devez avant tous avoir un code fonctionnel, ne perdez pas de temps sur des considérations esthétiques et supprimez les codes non fonctionnels.</span>**

**<span style="color:red"> 
Vous ne devez pas créer de nouveau bloque et vous répondrez aux questions uniquement dans les zones prévues.</span>**

Gestion du temps:
* Vous avez 2h30 pour traiter 25 questions, soit une moyenne de 6mn par question.
* Il y a des questions faciles auquelles vous repondrez en moins de 5mn.
* Vous pouvez toujours laisser une question en suspens pour y revenir après.
* Ne restez jamais bloquez plus de 10 mn sur une même question, allez à la question suivante.
* Le sujet n'est pas ordonné par difficulté. Des questions plus difficiles peuvent se trouver en début de sujet et des questions plus simple après.
    

2 - Sujet
-----    
    


In [2]:
import numpy as np

import scipy as sc
import scipy.optimize
import scipy.spatial
import scipy.signal

import matplotlib.pyplot as plt

In [3]:
# À compléter
id_etu = {
    "Nom": "Adouma",
    "Prénom": "hassan brahim",
    "Numéro d'étudiant": "21901741",
    "Groupe": "1A"
}    


In [4]:

# Ce bloc permet de valider votre code. Vous ne devez pas le modifier.  
try:
    assert len(id_etu['Nom'])>1,'Nom invalide'
    assert len(id_etu['Prénom'])>1,'Prénom invalide'
    assert any(chr.isdigit() for chr in id_etu["Numéro d'étudiant"]),"Numéro d'étudiant invalide"
    assert id_etu['Groupe'] in [str(i)+g for i in range(1,5) for g in 'AB' ],'Groupe invalide'
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    #raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.'))     
    

 Ok - Tous les tests sont validés.


Zone de commentaires:

---

Question 1: 
Définir une fonction retournant un tableau `Y` contenant les 39 plus grandes valeurs du tableau x passé en argument triées par ordre décroissant.


In [5]:

def f(x):
    Y=x[-39::]
    return Y


In [6]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = np.cos(np.arange(500)/13) * np.sin(np.arange(500)/54)
    Y = f(x)
    
    np.testing.assert_equal(Y.shape,(39,))
    np.testing.assert_equal(Y.max() < 1, True)
    np.testing.assert_equal(Y.min() > -1, True)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 2: 
Écrivez une fonction prenant une matrice `M` et déterminant dans quelles lignes de `M` se trouve la valeur `13`.
    
<span style="color:teal">Exemple :</span> <br>
Pour la matrice:

```
[[23 17 10 16  9 13]
 [13  7 22 21 10 23]
 [23 23 17 22 13 16]
 [13  8 13  6  7 22]
 [21 16 10 18 18 10]
 [10 11 21 22 11 14]]
```



la valeur `13` se trouve dans les lignes suivantes:

`[0 1 2 3]`
    

In [7]:

def fct(M):
    m=np.argwhere(M==13)
    return np.unique(m[:,0])
    

In [8]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[23, 17, 10, 16,  9, 13],
           [13,  7, 22, 21, 10, 23],
           [23, 23, 17, 22, 13, 16],
           [13,  8, 13,  6,  7, 22],
           [21, 16, 10, 18, 18, 10],
           [10, 11, 21, 22, 11, 14]])
    res = fct(M)
    np.testing.assert_equal(len(res),4,'Taille du vecteur incorrect.')
    np.testing.assert_equal(res,np.array([0, 1, 2, 3]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 3: 

Écrivez une fonction permettant de concaténer les tableaux `x` et `y` de taille [2 6] et [4 6] selon l'axe des ligne. 
 
<span style="color:teal">Exemple :</span> <br>
Sur les entrées 
```
[[7 1 2 4 2 0]
 [3 7 5 2 1 8]]
```
et
```
[[0 0 6 8 0 1]
 [4 5 6 4 8 8]
 [4 6 2 2 3 6]
 [0 1 0 3 5 0]]
```

le résultat attendu est 

```
[[7 1 2 4 2 0]
 [3 7 5 2 1 8]
 [0 0 6 8 0 1]
 [4 5 6 4 8 8]
 [4 6 2 2 3 6]
 [0 1 0 3 5 0]]
```


In [9]:

def fct(x,y):
    v=np.vstack((x,y))
    return v
    


In [10]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    x = np.random.random([2,6])
    y = np.random.random([4,6])
    res = fct(x,y)
    np.testing.assert_equal(res.shape,(6, 6),'Taille du tableau de sortie incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 4: 
Étant donné un vecteur `u` de taille 5, construisez une fonction retourrnant un vecteur de taille $30 = 5\times6$
où chaque élément de `u` est répété consécutivement 6 fois.

<span style="color:teal">Exemple :</span> <br>
À partir du vecteur:

```
[ 8  4  9 11  8]
```

on obtient:

```
[ 8  8  8  8  8  8  4  4  4  4  4  4  9  9  9  9  9  9 11 11 11 11 11 11
  8  8  8  8  8  8]
```
           

In [11]:

def fct(v):
    v=np.repeat(v,6)
    return v
    


In [12]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([ 8,  4,  9, 11,  8])
    res = fct(v)
    np.testing.assert_equal(np.sum(res),np.sum(v)*6,'Exemple incorrect.')
    np.testing.assert_equal(res,np.array([ 8,  8,  8,  8,  8,  8,  4,  4,  4,  4,  4,  4,  9,  9,  9,  9,  9,
            9, 11, 11, 11, 11, 11, 11,  8,  8,  8,  8,  8,  8]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 5: 
Écrivez une fonction qui prend en entrée une matrice et qui calcule la somme des éléments des colonnes de $3$ à $5$ (la colonne $5$ étant exclue). 

<span style="color:teal">Exemple :</span> <br>
```
[[6 1 1 4 3 6]
 [2 4 5 5 6 5]
 [4 3 6 2 5 2]
 [2 2 2 1 2 4]
 [3 6 1 6 1 2]]
```
<br>

a pour sortie `35`.


In [13]:

def amalgame(matrice):
    matrice=matrice[:,3:5]
    matrice=np.sum(matrice)
    return matrice



In [14]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
 
    res = amalgame(np.array([[6, 1, 1, 4, 3, 6], [2, 4, 5, 5, 6, 5], [4, 3, 6, 2, 5, 2], [2, 2, 2, 1, 2, 4], [3, 6, 1, 6, 1, 2]]))
    np.testing.assert_almost_equal(res,35)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 6:  À partir de 2 vecteurs v1 et v2, construisez à l'aide du broadcasting la matrice des multiplications entre les valeurs des deux vecteurs. 
Par exemple pour les vecteurs `[40 50]`  et  `[1 2 3 4 5]` la matrice retournée est la suivante :

```
[[ 40  80 120 160 200]
 [ 50 100 150 200 250]]
```

    

In [15]:

def fct(v1,v2):
    v1=v1.reshape((-1,1))
    v2=v2.reshape((-1,5))
    v=v1*v2
    return v


In [16]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    v1 = np.array([40, 50])
    v2 = np.array([1, 2, 3, 4, 5])
    res = fct(v1,v2)
    np.testing.assert_equal(list(res.shape),(len(v1),len(v2)),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[ 40,  80, 120, 160, 200],
           [ 50, 100, 150, 200, 250]]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 7: Définir un vecteur aléatoire `alea` de taille $25$ et dont les éléments sont des entiers compris entre $-6$ et $16$.

<span style='color:teal'> Exemple</span> <br>
`[11  2  9  1  8 14 10 11 12  0 11 10  4  0 15 -4 -6 -5 -5 -4  8  8  0 15
  1]`

In [17]:


def alea_int():
    alea=np.random.randint(-6,16,25)
    return alea



In [18]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
   
    alea = alea_int()
    np.testing.assert_equal(alea.size,25)
    np.testing.assert_equal(alea>=-6,True)
    np.testing.assert_equal(alea<=16,True)
    
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 8: 
Créer une fonction `inferieur` qui prend en entrée un tableau numpy et renvois 
un tableau de booléens de même taille que le tableau d'entrée contenant `True`
 si les valeurs du tableau d'entrée sont inferieur (strictement) à 0.5234, `False` sinon.


In [19]:

def inferieur(x):
    return x<0.5234
    

In [20]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = np.random.randn(50)
    
    np.testing.assert_equal(x.shape,inferieur(x).shape)
    np.testing.assert_equal(inferieur(x).dtype, np.dtype('bool'))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 9: 
Écrire une fonction `diagMatrice` qui construit et retourne une matrice carrée de taille $(9,9)$ dont les éléments sont de valeur $1$ exceptés ceux sur la $7$-ème diagonale (bas gauche -> haut droite) qui sont tous à $0$.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]]
```


In [21]:

def diagMatrice():
    v=np.ones((9,9))
    v[0,6]=0
    v[1,5]=0
    v[2,4]=0
    v[3,3]=0
    v[4,2]=0
    v[5,1]=0
    v[6,0]=0
    return v


In [22]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = diagMatrice()
    np.testing.assert_equal(mat.shape,(9,9))
    np.testing.assert_almost_equal(np.sum(mat),74)
    np.testing.assert_almost_equal(np.diag(mat[:7,6::-1]),0)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 10: 
Créez une matrice `mat` de taille (7,4) dont toutes les valeurs sont à 2 sauf la case (5,1) qui vaut 0.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 0. 2. 2.]
 [2. 2. 2. 2.]]
```


In [23]:

mat=np.full((7,4),2)
mat[5,1]=0
mat

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 0, 2, 2],
       [2, 2, 2, 2]])

In [24]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    np.testing.assert_equal(mat.shape,(7,4),err_msg='Attention à la taille')
    np.testing.assert_almost_equal(np.sum(mat),2*(7*4-1))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 11: 
Écrivez une fonction qui retourne la matrice construite en suivant les étapes suivantes:
- Construire le vecteur `v` constitué des entiers de 0 à 20 (exclu).
- Transformer `v` en la matrice suivante (en deux/trois instructions au plus).

```
[[19 15 11  7  3]
 [18 14 10  6  2]
 [17 13  9  5  1]
 [16 12  8  4  0]]
```
    

In [25]:

def fct():
    v=np.arange(0,20)
    v=v.reshape(5,4)
    v=v[::-1]
    v=np.transpose(v)
    v=v[::-1]

    return v
fct()


array([[19, 15, 11,  7,  3],
       [18, 14, 10,  6,  2],
       [17, 13,  9,  5,  1],
       [16, 12,  8,  4,  0]])

In [26]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    res = fct()
    np.testing.assert_equal(list(res.shape),(4, 5),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[19, 15, 11,  7,  3],
           [18, 14, 10,  6,  2],
           [17, 13,  9,  5,  1],
           [16, 12,  8,  4,  0]]),'Résultat incorrecte.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 12: Écrivez une fonction inversant l'ordre des éléments des lignes d'indice impair d'une matrice `M`.
           
<span style='color:teal'> Exemple</span> <br>
En partant de la matrice:
```
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]
 [22 23 24 25 26 27 28]
 [29 30 31 32 33 34 35]]
```


Le résultat attendu est:
```
[[ 1  2  3  4  5  6  7]
 [14 13 12 11 10  9  8]
 [15 16 17 18 19 20 21]
 [28 27 26 25 24 23 22]
 [29 30 31 32 33 34 35]]
```
    

In [62]:

def fct(M):
    M[1::2, :] = M[1::2, ::-1]
    return M
    


In [28]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[ 1,  2,  3,  4,  5,  6,  7],
           [ 8,  9, 10, 11, 12, 13, 14],
           [15, 16, 17, 18, 19, 20, 21],
           [22, 23, 24, 25, 26, 27, 28],
           [29, 30, 31, 32, 33, 34, 35]])
    res = fct(M)
    np.testing.assert_equal(res.shape,(5, 7),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[ 1,  2,  3,  4,  5,  6,  7],
           [14, 13, 12, 11, 10,  9,  8],
           [15, 16, 17, 18, 19, 20, 21],
           [28, 27, 26, 25, 24, 23, 22],
           [29, 30, 31, 32, 33, 34, 35]]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 13: 
Créez une matrice `mat` de taille (5,5) dont toutes les valeurs sont à 9 sauf la colonne 2 dont les éléments sont tous 0.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[9. 9. 0. 9. 9.]
 [9. 9. 0. 9. 9.]
 [9. 9. 0. 9. 9.]
 [9. 9. 0. 9. 9.]
 [9. 9. 0. 9. 9.]]
```


In [29]:
mat=np.full((5,5),9)
mat[:,2]=0
mat

array([[9, 9, 0, 9, 9],
       [9, 9, 0, 9, 9],
       [9, 9, 0, 9, 9],
       [9, 9, 0, 9, 9],
       [9, 9, 0, 9, 9]])

In [30]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    np.testing.assert_equal(mat.shape,(5,5),err_msg='Attention à la taille')
    np.testing.assert_almost_equal(np.sum(mat),9*5*(5-1))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 14: 
Créer un tableau numpy `x` contenant la liste des carrés des entiers allant de 9 à 12 (inclus).


In [31]:

def liste_carres():
    x=np.arange(9,13)
    x=x**2
    return x


In [32]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = liste_carres()
    np.testing.assert_equal(x.min(),9**2)
    np.testing.assert_equal(x.max(),12**2)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 15: 
Écrivez une fonction `suppresseColonne` qui prend en entrée une matrice et qui supprime de cette matrice toutes les colonnes qui contiennent la valeur 16

<span style="color:teal">Exemple :</span> <br>
```
[[24 19 25 -5 11  0  6]
 [23 -2  4  5  8 10 -5]
 [21 -5 21 21 16 21  4]]
```
<br>

a pour sortie:

```
[[24 19 25 -5  0  6]
 [23 -2  4  5 10 -5]
 [21 -5 21 21 21  4]]
```


In [33]:

def suppresseColonne(matrice):
    matrice=np.argwhere(matrice == 16)
    matrice=np.delete(matrice,matrice[:,0])
    return matrice
    


In [34]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = np.arange(24)
    mat[np.random.randint(24)] = 16
    mat[np.random.randint(24)] = 16
    mat = mat.reshape((4,-1))
    res = suppresseColonne(mat)
    np.testing.assert_equal(mat.shape[0],res.shape[0])
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 16: 
Écrire une fonction qui prend en entrée une matrice de taille $(7,3)$ et qui soustrait la ligne $4$ à toutes les lignes de la matrice.

<span style="color:teal">Exemple :</span> <br>
```
[[5 3 5]
 [3 6 6]
 [1 5 6]
 [3 2 5]
 [2 5 4]
 [3 3 3]
 [6 2 2]]
```
<br>

a pour sortie

```
[[ 3 -2  1]
 [ 1  1  2]
 [-1  0  2]
 [ 1 -3  1]
 [ 0  0  0]
 [ 1 -2 -1]
 [ 4 -3 -2]]
```


In [35]:

def soustrait(matrice):
    s=matrice[4,:]
    matrice=matrice - s
    return matrice

In [36]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = np.arange(7*3).reshape(-1,3)
    res = soustrait(mat)
    np.testing.assert_equal(res.shape,mat.shape)
    np.testing.assert_almost_equal(np.sum(res),np.sum(mat)-7*np.sum(mat[4]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 17: 
Écrivez une fonction qui prend en entrée une matrice, et qui retourne la sous-matrice de taille $(7,7)$ qui forme le coin en bas à gauche de la matrice.

<span style="color:teal"> Exemple</span> <br>
Pour une matrice:
```
[[6 3 6 1 4 1 1 1 5 4 5 5 5 2 2 5 2 5 2 2]
 [1 5 5 1 5 6 3 6 5 4 5 4 1 4 1 4 6 1 2 2]
 [2 6 3 6 2 5 3 1 3 5 2 1 6 4 5 1 6 1 3 3]
 [6 4 1 4 6 3 5 6 2 1 4 5 4 2 6 1 3 2 5 6]
 [2 2 3 2 3 5 2 6 6 4 6 3 5 4 5 4 1 5 4 6]
 [1 5 3 6 5 1 2 5 4 6 3 3 2 5 3 4 6 2 1 3]
 [5 5 4 2 5 4 6 6 5 3 5 3 4 6 4 4 2 4 5 3]
 [3 2 6 5 1 5 4 2 6 1 3 5 6 1 6 5 4 3 6 3]
 [6 6 1 4 1 4 4 4 2 2 4 6 1 6 4 4 2 2 4 4]
 [2 1 1 2 4 2 3 4 2 1 3 5 2 6 3 3 2 3 6 4]
 [5 5 1 3 6 1 3 5 5 1 6 4 6 6 4 5 6 2 1 3]
 [6 6 6 4 2 1 4 6 1 2 4 4 6 3 4 2 5 4 5 2]
 [5 6 1 1 2 3 3 1 3 4 6 6 1 5 3 4 3 6 6 3]
 [4 4 3 4 6 3 6 6 4 4 1 5 4 2 3 6 6 3 6 4]
 [4 1 1 6 4 5 3 1 3 1 6 1 3 2 4 3 5 1 6 6]
 [5 3 5 1 6 1 3 3 4 1 1 1 1 6 5 3 2 6 3 5]
 [4 6 5 2 2 6 1 3 1 3 2 5 2 6 1 6 2 4 6 2]
 [6 1 2 2 5 1 3 5 6 1 1 6 3 5 6 1 5 2 2 4]
 [1 3 5 3 1 3 6 2 3 1 6 6 6 5 5 4 6 3 1 3]
 [4 1 3 3 5 3 5 5 4 3 1 5 2 3 3 1 1 6 3 1]]
```
<br>

le coin en bas à gauche est :
```
[[4 4 3 4 6 3 6]
 [4 1 1 6 4 5 3]
 [5 3 5 1 6 1 3]
 [4 6 5 2 2 6 1]
 [6 1 2 2 5 1 3]
 [1 3 5 3 1 3 6]
 [4 1 3 3 5 3 5]]
```


In [37]:
 
def extraire(matrice):
    matrice=matrice[-7:,0:7]
    return matrice



In [38]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    matrice = np.random.randint(1,7,size=(20,20))
    res = extraire(matrice)
    np.testing.assert_equal(res.shape,(7,7))
    if 0==0:
        np.testing.assert_equal(res[-1,0],matrice[-1,0])
    elif 0==1:
        np.testing.assert_equal(res[-1,-1],matrice[-1,-1])
    else:
        np.testing.assert_equal(res[0,-1],matrice[0,-1])
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 18: 
Ecrire une fonction `mesure` qui retourne la norme euclidienne d'un vecteur de taille quelconque.


In [39]:

def mesure(x):
    return np.linalg.norm(x)


In [40]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    
    x = np.arange(2)
    d1 = mesure(x)
    
    np.testing.assert_equal(d1,1.0)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 19: Étant donnée une matrice `M`, écrivez une fonction retournant tous les indices de(s) ligne(s) de `M` contenant la valeur minimale .
    
<span style="color:teal">Exemple :</span> <br>
Pour la matrice:
```
[[45 22 34 13 36  8 12]
 [ 7 49 18  8 48 15 13]
 [30 24  8 14 52 55 48]
 [38 22 39 17 32 33 12]
 [41 16 27  7 25 29 23]
 [ 6 45 36 24 47 34 36]
 [12 40 51 40 29 30 17]
 [ 7 47 41 27 21 39 30]]
```

la valeur minimale (ici 6) se trouve aux ligne d'indices: `[5]`.
    

In [60]:

def fct(M):
    m=np.argwhere(M == np.min(M))
    return m[:,0]
    

v=np.array([[45, 22, 34, 13 ,36 , 8 ,12],
            [ 7, 49, 18 , 8, 48 ,15 ,13],
            [30 ,24 , 8 ,14, 52, 55 ,48],
            [38, 22, 39, 17, 32, 33 ,12],
            [41, 16, 27 , 7, 25 ,29, 23],
            [ 6 ,45 ,36, 24, 47, 34, 36],
            [12 ,40, 51, 40, 29, 30, 17],
            [ 7 ,47 ,41 ,27 ,21 ,39, 30]])
res=fct(v)
print(res)


[5]


In [61]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[45, 22, 34, 13, 36,  8, 12],
           [ 7, 49, 18,  8, 48, 15, 13],
           [30, 24,  8, 14, 52, 55, 48],
           [38, 22, 39, 17, 32, 33, 12],
           [41, 16, 27,  7, 25, 29, 23],
           [ 6, 45, 36, 24, 47, 34, 36],
           [12, 40, 51, 40, 29, 30, 17],
           [ 7, 47, 41, 27, 21, 39, 30]])
    res = fct(M)
    np.testing.assert_equal(len(res),1,'Nombre de sortie incorrecte.')
    np.testing.assert_equal(res,np.array([5]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 20: 
Écrire une fonction qui prend en entrée un vecteur dont la longueur est un multiple de 3,
et qui retourne le minimum de chaque séquence de 3 éléments consécutifs.

<span style="color:teal">Exemple :</span> <br>
`[11 14  0 10  7 10  3  7 13 14  3  6 11  3  8  6  8  1  4  3  6 13 12 13
  1 14  4 13  5 10]`

a pour sortie

`[ 0  7  3  3  3  1  3 12  1  5]`


In [43]:

def consecutif(vecteur):
    v=vecteur.reshape((-1,3))
    return np.min(v,axis=1)
    
    


In [44]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    vv = np.random.randint(1,15,8*3)
    res = consecutif(vv)
    np.testing.assert_equal(len(vv),3*len(res))
    np.testing.assert_equal(res[2:],consecutif(vv[(2*3):]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 21: 

Étant donné un vecteur `v`, écrivez une fonction qui remplace tous les éléments de `v` qui sont inférieurs à 6 par -3, et tous les éléments qui sont supérieurs à 18 par 2.

<span style="color:teal">Exemple :</span> <br>
`[ 3 13  6 18  8  9 19 11]`

a pour sortie:

`[-3 13  6 18  8  9  2 11]`
    

In [45]:

def fct(v):
    v[v<6],v[v>18]=-3,2
    return v


In [46]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([ 3, 13,  6, 18,  8,  9, 19, 11])
    res = fct(v)
    np.testing.assert_equal(res,np.array([-3, 13,  6, 18,  8,  9,  2, 11]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 22: 

Étant donné un vecteur, écrivez une fonction qui détermine si ce vecteur est strictement décroissant ou non. Pour cette question, vous pouvez utiliser une convolution pour calculer la soustraction entre valeur consécutive et en déduire le résultat attendu.
 
<span style="color:teal">Exemple :</span> <br>
Sur l'entrée `[29 28 21 18 13 11  8  4  2]` est renvoyé True



In [47]:

def fct(v):
    v1 = v[0:-1]
    v2 = v[1:]
    return np.all((v1-v2)>0)
    


In [48]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([29, 28, 21, 18, 13, 11,  8,  4,  2])
    res = fct(v)
    np.testing.assert_equal(res,True,'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 23: Écrivez une fonction qui retourne les 5 plus petits éléments d'un vecteur `v` trié du plus petit au plus grand.

<span style="color:teal">Exemple :</span> <br>

Les 5 plus petits éléments de `[13 56 16 24 54 29 22  4  0 13 60 40]` sont `[ 0  4 13 13 16]`
    

In [49]:

def fct(v):
    v=np.sort(v)
    v=v[0:5]
    return v

In [50]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([13, 56, 16, 24, 54, 29, 22,  4,  0, 13, 60, 40])
    res = fct(v)
    np.testing.assert_equal(len(res),5,'Taille du vecteur incorrect.')
    np.testing.assert_equal(res,np.array([ 0,  4, 13, 13, 16]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 24: 
Écrivez une fonction prenant en entrée un vecteur et retournant un tableau de tous les éléments qui sont strictement supérieurs à 4.

<span style="color:teal">Exemple :</span> <br>
`[6 4 0 6 2 5 0 3 6]` a pour sortie `[6 6 5 6]`
    

In [51]:

def fct(v):
    v=v[v>4]
    return v


In [52]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    
    v = np.array([6,4,0,6,2,5,0,3,6])
    np.testing.assert_equal(fct(v),np.array([6,6,5,6]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 25: 
En utilisant le mécanisme de broadcasting, écrire une fonction `distance_minkowski_matrix` prenant en entrée une matrice
`P` de $n$ lignes (points) et $k$ colonnes (coordonnées) et qui renvois la matrice `D` de taille $n \times n$ tel que $D_{i,j} = \left(\sum_{c=1}^k \left(P_{i,c}-P_{j,c}\right)^6\right)^\frac{1}{6}$ .


In [1]:

def distance_minkowski_matrix(P):
    tmp = P[::,np.newaxis]
    tmp = np.power((tmp-P),6)
    D=np.power(np.sum(tmp,axis=2),1/6)
    return D


In [2]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    a = np.random.randint(0,10,(10,2))*2-1
    b = distance_minkowski_matrix(a)
    
    np.testing.assert_equal(b.shape,(10,10),err_msg='Dimensions non valident.')
    np.testing.assert_almost_equal((b < 0.0).sum(), 0,err_msg='Les valeurs calculés sont fausses.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 KO - Au moins un test n'est pas validé
Information sur le test non valide:
name 'np' is not defined


NameError: name 'np' is not defined