
TP noté de Calcul scientifique
 =====
 
1 - Consignes 
-----

L'examen sera à réaliser en python 3. Les questions du sujet doivent être résolues uniquement avec des fonctions des librairies `numpy`, `scipy` et `matplotlib` vu durant l'année.
	
**<span style="color:red"> À part si cela est précisé, vous ne devez pas utiliser directement de boucle (`for`,`while`) ou de branchement conditionnel (`if`).</span>.**

**<span style="color:red"> 
Vous rendrez ce notebook en fin d'examen sur la plateforme ecampus sans en changer le nom. Les réponses sont à mettre dans le présent notebook et non dans un autre fichier.</span>**

**<span style="color:red"> 
Aucun envoi par mail ou soumission en retard ne sera accepté.</span>**

**<span style="color:red"> 
Vous devez avant tous avoir un code fonctionnel, ne perdez pas de temps sur des considérations esthétiques et supprimez les codes non fonctionnels.</span>**

**<span style="color:red"> 
Vous ne devez pas créer de nouveau bloque et vous répondrez aux questions uniquement dans les zones prévues.</span>**

Gestion du temps:
* Vous avez 2h30 pour traiter 25 questions, soit une moyenne de 6mn par question.
* Il y a des questions faciles auquelles vous repondrez en moins de 5mn.
* Vous pouvez toujours laisser une question en suspens pour y revenir après.
* Ne restez jamais bloquez plus de 10 mn sur une même question, allez à la question suivante.
* Le sujet n'est pas ordonné par difficulté. Des questions plus difficiles peuvent se trouver en début de sujet et des questions plus simple après.
    

2 - Sujet
-----    
    


In [57]:
import numpy as np

import scipy as sc
import scipy.optimize
import scipy.spatial
import scipy.signal

import matplotlib.pyplot as plt

In [58]:
# À compléter
id_etu = {
    "Nom": "NTORE ",
    "Prénom": "HUGUES",
    "Numéro d'étudiant": "2221à884",
    "Groupe": "4A"
}    


In [59]:

# Ce bloc permet de valider votre code. Vous ne devez pas le modifier.  
try:
    assert len(id_etu['Nom'])>1,'Nom invalide'
    assert len(id_etu['Prénom'])>1,'Prénom invalide'
    assert any(chr.isdigit() for chr in id_etu["Numéro d'étudiant"]),"Numéro d'étudiant invalide"
    assert id_etu['Groupe'] in [str(i)+g for i in range(1,5) for g in 'AB' ],'Groupe invalide'
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    #raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.'))     
    

 Ok - Tous les tests sont validés.


Zone de commentaires:

---

Question 1: 
Écrire une fonction qui prend en entrée une matrice de taille $(5,2)$ et qui soustrait la ligne $2$ à toutes les lignes de la matrice.

<span style="color:teal">Exemple :</span> <br>
```
[[5 6]
 [5 2]
 [3 5]
 [5 5]
 [3 3]]
```
<br>

a pour sortie

```
[[ 2  1]
 [ 2 -3]
 [ 0  0]
 [ 2  0]
 [ 0 -2]]
```


In [60]:

def soustrait(matrice):
    return matrice - matrice[2,:]

In [61]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = np.arange(5*2).reshape(-1,2)
    res = soustrait(mat)
    np.testing.assert_equal(res.shape,mat.shape)
    np.testing.assert_almost_equal(np.sum(res),np.sum(mat)-5*np.sum(mat[2]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 2: 
Écrivez une fonction qui prend en entrée une matrice et qui calcule le produit des éléments des colonnes de $2$ à $4$ (la colonne $4$ étant exclue). 

<span style="color:teal">Exemple :</span> <br>
```
[[3 6 6 4 3 6]
 [3 3 2 2 3 5]]
```
<br>

a pour sortie `96`.


In [62]:

def amalgame(matrice):
    return np.prod(matrice[:,2:4])


In [63]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
 
    res = amalgame(np.array([[3, 6, 6, 4, 3, 6], [3, 3, 2, 2, 3, 5]]))
    np.testing.assert_almost_equal(res,96)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 3: Définir un vecteur aléatoire `alea` de taille $15$ et dont les éléments sont des entiers compris entre $-7$ et $17$.

<span style='color:teal'> Exemple</span> <br>
`[-6  9 -5 -5 -2 14  6  7 -3 15 -4 14 -3 14  1]`

In [64]:


def alea_int():
   alea=np.linspace(-7,17,num=15)
   return alea



In [65]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
   
    alea = alea_int()
    np.testing.assert_equal(alea.size,15)
    np.testing.assert_equal(alea>=-7,True)
    np.testing.assert_equal(alea<=17,True)
    
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 4: 
Créez une matrice `mat` de taille (6,6) dont toutes les valeurs sont à 4 sauf la colonne 4 dont les éléments sont tous 0.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[4. 4. 4. 4. 0. 4.]
 [4. 4. 4. 4. 0. 4.]
 [4. 4. 4. 4. 0. 4.]
 [4. 4. 4. 4. 0. 4.]
 [4. 4. 4. 4. 0. 4.]
 [4. 4. 4. 4. 0. 4.]]
```


In [66]:

mat=np.full((6,6),4)
mat[:,4]=np.zeros(6)


In [67]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    np.testing.assert_equal(mat.shape,(6,6),err_msg='Attention à la taille')
    np.testing.assert_almost_equal(np.sum(mat),4*6*(6-1))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 5: 

Étant donné un vecteur `v`, écrivez une fonction qui remplace tous les éléments de `v` qui sont inférieurs à 10 par -2, et tous les éléments qui sont supérieurs à 12 par 4.

<span style="color:teal">Exemple :</span> <br>
`[ 4  4 15  9  7  8]`

a pour sortie:

`[-2 -2  4 -2 -2 -2]`
    

In [68]:

def fct(v):
    v[v<10]=-2
    v[v>12]=4
    return v


In [69]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([ 4,  4, 15,  9,  7,  8])
    res = fct(v)
    np.testing.assert_equal(res,np.array([-2, -2,  4, -2, -2, -2]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 6: 
Écrire une fonction qui prend en entrée un vecteur dont la longueur est un multiple de 5,
et qui retourne le maximum de chaque séquence de 5 éléments consécutifs.

<span style="color:teal">Exemple :</span> <br>
`[11  7  9  1  6  0  0 10  0  4  6  4  3  2  3 12 12  5  4 10 14 12  9  0
  5  3  8 12  8 14 10  6 10  8  7  1 13 13 14  5 11 13  9  4  9  7  2  2
 10  3]`

a pour sortie

`[11 10  6 12 14 14 10 14 13 10]`


In [70]:

def consecutif(vecteur):
    return np.max(vecteur.reshape((int(vecteur.size/5),5)),axis=1)



In [71]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    vv = np.random.randint(1,15,8*5)
    res = consecutif(vv)
    np.testing.assert_equal(len(vv),5*len(res))
    np.testing.assert_equal(res[2:],consecutif(vv[(2*5):]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 7: 
En utilisant le mécanisme de broadcasting, écrire une fonction `distance_minkowski_matrix` prenant en entrée une matrice
`P` de $n$ lignes (points) et $k$ colonnes (coordonnées) et qui renvois la matrice `D` de taille $n \times n$ tel que $D_{i,j} = \left(\sum_{c=1}^k \left(P_{i,c}-P_{j,c}\right)^2\right)^\frac{1}{2}$ .


In [72]:

def distance_minkowski_matrix(P):
    tmp = P[:,np.newaxis]
    tmp = np.power((tmp-P),2)
    D=np.power(np.sum(tmp,axis=2),1/2)
    return D
    

In [73]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    a = np.random.randint(0,10,(10,2))*2-1
    b = distance_minkowski_matrix(a)
    
    np.testing.assert_equal(b.shape,(10,10),err_msg='Dimensions non valident.')
    np.testing.assert_almost_equal((b < 0.0).sum(), 0,err_msg='Les valeurs calculés sont fausses.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 8: 
Écrivez une fonction prenant en entrée un vecteur et retournant un tableau de tous les éléments qui sont supérieurs ou égals à 3.

<span style="color:teal">Exemple :</span> <br>
`[5 6 2 0 0 2 3]` a pour sortie `[5 6 3]`
    

In [74]:

def fct(v):
    return v[v>=3]
    


In [75]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    
    v = np.array([5,6,2,0,0,2,3])
    np.testing.assert_equal(fct(v),np.array([5,6,3]))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 9: 
Ecrire une fonction `mesure` qui retourne la norme euclidienne d'un vecteur de taille quelconque.


In [76]:

def mesure(x):
    return np.linalg.norm(x)


In [77]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    
    x = np.arange(2)
    d1 = mesure(x)
    
    np.testing.assert_equal(d1,1.0)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 10: 
Créez une matrice `mat` de taille (7,2) dont toutes les valeurs sont à 2 sauf la case (4,0) qui vaut 0.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[2. 2.]
 [2. 2.]
 [2. 2.]
 [2. 2.]
 [0. 2.]
 [2. 2.]
 [2. 2.]]
```


In [78]:
mat=np.full((7,2),2)
mat[4,0]=0


In [79]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    np.testing.assert_equal(mat.shape,(7,2),err_msg='Attention à la taille')
    np.testing.assert_almost_equal(np.sum(mat),2*(7*2-1))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 11: 
Créer un tableau numpy `x` contenant la liste des carrés des entiers allant de 1 à 14 (inclus).


In [80]:

def liste_carres():
    return np.power(np.arange(1,15),2)


In [81]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = liste_carres()
    np.testing.assert_equal(x.min(),1**2)
    np.testing.assert_equal(x.max(),14**2)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 12: 
Créer une fonction `inferieur` qui prend en entrée un tableau numpy et renvois 
un tableau de booléens de même taille que le tableau d'entrée contenant `False`
 si les valeurs du tableau d'entrée sont inferieur (strictement) à -0.8756, `True` sinon.


In [82]:

def inferieur(x):
    return x<-0.8756


In [83]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = np.random.randn(50)
    
    np.testing.assert_equal(x.shape,inferieur(x).shape)
    np.testing.assert_equal(inferieur(x).dtype, np.dtype('bool'))
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 13:  À partir de 2 vecteurs v1 et v2, construisez à l'aide du broadcasting la matrice des multiplications entre les valeurs des deux vecteurs. 
Par exemple pour les vecteurs `[40 50 60 70]`  et  `[1 2 3 4 5]` la matrice retournée est la suivante :

```
[[ 40  80 120 160 200]
 [ 50 100 150 200 250]
 [ 60 120 180 240 300]
 [ 70 140 210 280 350]]
```

    

In [84]:

def fct(v1,v2):
   v1=v1[:,np.newaxis]
   v2=v2[np.newaxis,:]
   return v1*v2
v1 = np.array([40, 50, 60, 70])
v2 = np.array([1, 2, 3, 4, 5])
res = fct(v1,v2)

In [85]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    v1 = np.array([40, 50, 60, 70])
    v2 = np.array([1, 2, 3, 4, 5])
    res = fct(v1,v2)
    np.testing.assert_equal(list(res.shape),(len(v1),len(v2)),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[ 40,  80, 120, 160, 200],
           [ 50, 100, 150, 200, 250],
           [ 60, 120, 180, 240, 300],
           [ 70, 140, 210, 280, 350]]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 14: 

Écrivez une fonction permettant de concaténer les tableaux `x` et `y` de taille [2 7] et [6 7] selon l'axe des ligne. 
 
<span style="color:teal">Exemple :</span> <br>
Sur les entrées 
```
[[5 4 3 4 0 5 1]
 [7 1 1 2 8 2 2]]
```
et
```
[[4 5 7 7 1 3 1]
 [4 4 0 5 5 4 2]
 [3 8 8 0 7 6 8]
 [4 1 8 3 3 3 2]
 [5 4 5 6 5 8 2]
 [1 3 6 5 3 0 7]]
```

le résultat attendu est 

```
[[5 4 3 4 0 5 1]
 [7 1 1 2 8 2 2]
 [4 5 7 7 1 3 1]
 [4 4 0 5 5 4 2]
 [3 8 8 0 7 6 8]
 [4 1 8 3 3 3 2]
 [5 4 5 6 5 8 2]
 [1 3 6 5 3 0 7]]
```


In [86]:

def fct(x,y):
    return np.vstack((x,y))
x = np.random.random([2,7])
y = np.random.random([6,7])
res = fct(x,y) 


In [87]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    x = np.random.random([2,7])
    y = np.random.random([6,7])
    res = fct(x,y)
    np.testing.assert_equal(res.shape,(8, 7),'Taille du tableau de sortie incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 15: 
Écrivez une fonction qui retourne la matrice construite en suivant les étapes suivantes:
- Construire le vecteur `v` constitué des entiers de 1 à 21 (exclu).
- Transformer `v` en la matrice suivante (en deux/trois instructions au plus).

```
[[20 15 10  5]
 [19 14  9  4]
 [18 13  8  3]
 [17 12  7  2]
 [16 11  6  1]]
```
    

In [88]:

def fct():
    v=np.arange(1,21)[::-1]
    return np.transpose(v.reshape((int(v.size/5),5)))
fct()

array([[20, 15, 10,  5],
       [19, 14,  9,  4],
       [18, 13,  8,  3],
       [17, 12,  7,  2],
       [16, 11,  6,  1]])

In [89]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    res = fct()
    np.testing.assert_equal(list(res.shape),(5, 4),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[20, 15, 10,  5],
           [19, 14,  9,  4],
           [18, 13,  8,  3],
           [17, 12,  7,  2],
           [16, 11,  6,  1]]),'Résultat incorrecte.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 16: 
Écrivez une fonction `suppresseColonne` qui prend en entrée une matrice et qui supprime de cette matrice toutes les colonnes qui contiennent la valeur 22

<span style="color:teal">Exemple :</span> <br>
```
[[16 17 14  1 20 22]
 [17  8 12 14 -2  6]
 [ 3 15 16 21  5  1]
 [24 22 16 -2 -2 25]
 [ 1 22 13  7 22 23]]
```
<br>

a pour sortie:

```
[[16 14  1]
 [17 12 14]
 [ 3 16 21]
 [24 16 -2]
 [ 1 13  7]]
```


In [90]:

def suppresseColonne(matrice):
    return matrice[:, ~np.any(matrice==22, axis=0)]
   


In [91]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = np.arange(24)
    mat[np.random.randint(24)] = 22
    mat[np.random.randint(24)] = 22
    mat = mat.reshape((4,-1))
    res = suppresseColonne(mat)
    np.testing.assert_equal(mat.shape[0],res.shape[0])
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 17: Étant donnée une matrice `M`, écrivez une fonction retournant tous les indices de(s) ligne(s) de `M` contenant la valeur maximale .
    
<span style="color:teal">Exemple :</span> <br>
Pour la matrice:
```
[[22 25 27 15]
 [13  4 19 15]
 [16 22  7 26]
 [23 29 33 18]
 [ 9 14 25 21]
 [21 35 35 26]
 [33 35  9 18]
 [19  9 17 27]
 [21  4 20 26]]
```

la valeur maximale (ici 35) se trouve aux ligne d'indices: `[5 6]`.
    

In [92]:

def fct(M):
    x=np.argwhere(M==np.max(M))[:,0]
    return np.unique(x)




In [93]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[22, 25, 27, 15],
           [13,  4, 19, 15],
           [16, 22,  7, 26],
           [23, 29, 33, 18],
           [ 9, 14, 25, 21],
           [21, 35, 35, 26],
           [33, 35,  9, 18],
           [19,  9, 17, 27],
           [21,  4, 20, 26]])
    res = fct(M)
    np.testing.assert_equal(len(res),2,'Nombre de sortie incorrecte.')
    np.testing.assert_equal(res,np.array([5, 6]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 18: 
Étant donné un vecteur `u` de taille 5, construisez une fonction retourrnant un vecteur de taille $15 = 5\times3$
où chaque élément de `u` est répété consécutivement 3 fois.

<span style="color:teal">Exemple :</span> <br>
À partir du vecteur:

```
[13 13  7  8 11]
```

on obtient:

```
[13 13 13 13 13 13  7  7  7  8  8  8 11 11 11]
```
           

In [94]:

def fct(v):
    return np.repeat(v,3)
    


In [95]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([13, 13,  7,  8, 11])
    res = fct(v)
    np.testing.assert_equal(np.sum(res),np.sum(v)*3,'Exemple incorrect.')
    np.testing.assert_equal(res,np.array([13, 13, 13, 13, 13, 13,  7,  7,  7,  8,  8,  8, 11, 11, 11]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 19: 
Écrire une fonction `diagMatrice` qui construit et retourne une matrice carrée de taille $(9,9)$ dont les éléments sont de valeur $3$ exceptés ceux sur la $3$-ème diagonale (bas gauche -> haut droite) qui sont tous à $0$.

<span style="color:teal">La matrice à construire :</span> <br>
```
[[3. 3. 0. 3. 3. 3. 3. 3. 3.]
 [3. 0. 3. 3. 3. 3. 3. 3. 3.]
 [0. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3.]]
```


In [96]:

def diagMatrice():
    res=np.full((9,9),3)
    res[0,2]=0
    res[2,0]=0
    res[1,1]=0
    return res
    


In [97]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    mat = diagMatrice()
    np.testing.assert_equal(mat.shape,(9,9))
    np.testing.assert_almost_equal(np.sum(mat),234)
    np.testing.assert_almost_equal(np.diag(mat[:3,2::-1]),0)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 20: Écrivez une fonction inversant l'ordre des éléments des colonnes d'indice impair d'une matrice `M`.
           
<span style='color:teal'> Exemple</span> <br>
En partant de la matrice:
```
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
```


Le résultat attendu est:
```
[[ 1 17  3 19  5]
 [ 6 12  8 14 10]
 [11  7 13  9 15]
 [16  2 18  4 20]]
```
    

In [98]:

def fct(M):
    M[:,1::2] = M[::-1,1::2]
    return M
    

In [99]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[ 1,  2,  3,  4,  5],
           [ 6,  7,  8,  9, 10],
           [11, 12, 13, 14, 15],
           [16, 17, 18, 19, 20]])
    res = fct(M)
    np.testing.assert_equal(res.shape,(4, 5),'Taille de la matrice incorrecte.')
    np.testing.assert_equal(res,np.array([[ 1, 17,  3, 19,  5],
           [ 6, 12,  8, 14, 10],
           [11,  7, 13,  9, 15],
           [16,  2, 18,  4, 20]]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 21: 
Définir une fonction retournant un tableau `Y` contenant les 78 plus grandes valeurs du tableau x passé en argument triées par ordre décroissant.


In [100]:

def f(x):
    return np.sort(x,axis=0)[-1:-79:-1]


In [101]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    x = np.cos(np.arange(500)/13) * np.sin(np.arange(500)/71)
    Y = f(x)
    
    np.testing.assert_equal(Y.shape,(78,))
    np.testing.assert_equal(Y.max() < 1, True)
    np.testing.assert_equal(Y.min() > -1, True)
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 22: Écrivez une fonction qui retourne les 4 plus grands éléments d'un vecteur `v` trié du plus petit au plus grand.

<span style="color:teal">Exemple :</span> <br>

Les 4 plus grands éléments de `[ 1 52 69 13 32 60 59  0 16 95 22 37]` sont `[59 60 69 95]`
    

In [102]:

def fct(v):
    x=v.size
    return np.sort(v)[x-4:x:1]


In [103]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([ 1, 52, 69, 13, 32, 60, 59,  0, 16, 95, 22, 37])
    res = fct(v)
    np.testing.assert_equal(len(res),4,'Taille du vecteur incorrect.')
    np.testing.assert_equal(res,np.array([59, 60, 69, 95]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 23: 

Étant donné un vecteur, écrivez une fonction qui détermine si ce vecteur est décroissant ou non. Pour cette question, vous pouvez utiliser une convolution pour calculer la soustraction entre valeur consécutive et en déduire le résultat attendu.
 
<span style="color:teal">Exemple :</span> <br>
Sur l'entrée `[27 25 24 24 23 15 11  3  2]` est renvoyé True



In [104]:

def fct(v):
    
    raise NotImplementedError()
    


In [105]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    v = np.array([27, 25, 24, 24, 23, 15, 11,  3,  2])
    res = fct(v)
    np.testing.assert_equal(res,True,'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 KO - Au moins un test n'est pas validé
Information sur le test non valide:



NotImplementedError: 

Question 24: 
Écrivez une fonction qui prend en entrée une matrice, et qui retourne la sous-matrice de taille $(11,11)$ qui forme le coin en bas à droite de la matrice.

<span style="color:teal"> Exemple</span> <br>
Pour une matrice:
```
[[4 4 5 4 1 5 5 5 5 5 1 3 4 6 5 3 5 1 2 1]
 [4 6 1 6 2 3 4 5 5 1 2 2 3 4 3 3 2 3 3 6]
 [5 2 1 2 4 4 2 4 5 1 4 3 2 5 5 2 4 1 6 6]
 [2 5 5 1 3 4 5 4 2 2 6 1 5 2 1 4 4 2 6 2]
 [3 5 3 6 1 4 6 1 6 4 3 3 3 1 5 1 4 3 3 2]
 [5 2 4 1 1 2 5 1 2 3 3 5 1 3 4 5 5 1 2 2]
 [2 4 6 5 4 5 6 2 5 3 6 1 2 2 2 6 6 1 4 4]
 [3 3 4 3 6 2 1 6 6 1 5 6 4 1 4 1 1 6 4 6]
 [4 1 6 5 5 3 5 6 5 2 6 3 4 4 1 1 3 1 2 5]
 [6 3 4 2 5 1 3 2 2 5 6 4 6 6 1 1 1 5 2 6]
 [3 4 6 2 5 1 3 3 4 4 2 3 3 1 6 4 2 3 2 4]
 [2 3 4 1 5 5 4 4 2 2 6 4 3 1 5 2 1 1 3 2]
 [6 2 6 3 5 3 2 6 1 6 6 3 4 3 4 3 3 6 1 1]
 [6 4 2 2 3 3 1 6 3 2 4 4 4 6 3 1 5 1 6 5]
 [4 5 4 3 1 6 3 1 6 6 6 6 6 5 1 5 5 6 2 6]
 [4 2 3 3 2 2 3 5 5 1 4 6 1 4 1 1 6 3 4 2]
 [5 1 5 2 4 5 6 6 1 6 3 6 5 2 2 4 4 5 1 2]
 [3 2 4 2 5 4 4 1 1 2 2 5 4 4 5 6 1 4 4 3]
 [5 3 6 2 3 6 3 4 2 3 5 2 6 6 2 3 1 5 4 3]
 [6 3 1 6 6 3 4 4 2 6 1 2 4 3 3 4 2 2 1 3]]
```
<br>

le coin en bas à droite est :
```
[[5 6 4 6 6 1 1 1 5 2 6]
 [4 2 3 3 1 6 4 2 3 2 4]
 [2 6 4 3 1 5 2 1 1 3 2]
 [6 6 3 4 3 4 3 3 6 1 1]
 [2 4 4 4 6 3 1 5 1 6 5]
 [6 6 6 6 5 1 5 5 6 2 6]
 [1 4 6 1 4 1 1 6 3 4 2]
 [6 3 6 5 2 2 4 4 5 1 2]
 [2 2 5 4 4 5 6 1 4 4 3]
 [3 5 2 6 6 2 3 1 5 4 3]
 [6 1 2 4 3 3 4 2 2 1 3]]
```


In [ ]:
 
def extraire(matrice):
   x,y=matrice.shape
   return matrice[x-11:,y-11:]



In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:

    matrice = np.random.randint(1,7,size=(20,20))
    res = extraire(matrice)
    np.testing.assert_equal(res.shape,(11,11))
    if 1==0:
        np.testing.assert_equal(res[-1,0],matrice[-1,0])
    elif 1==1:
        np.testing.assert_equal(res[-1,-1],matrice[-1,-1])
    else:
        np.testing.assert_equal(res[0,-1],matrice[0,-1])
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.


Question 25: 
Écrivez une fonction prenant une matrice `M` et déterminant dans quelles colonnes de `M` se trouve la valeur `28`.
    
<span style="color:teal">Exemple :</span> <br>
Pour la matrice:

```
[[ 7 21  8 12 28 20]
 [29 28 28  9 27 16]
 [29  7 28  7 27 26]
 [10 10  8 22 26 12]
 [33 22 28  5 26 18]
 [14 28 34  9 31 26]
 [ 4 15 32 23  4 34]
 [20 20 17 19 31  8]
 [20  5  3 27 25 24]]
```



la valeur `28` se trouve dans les colonnes suivantes:

`[1 2 4]`
    

In [ ]:

def fct(M):
    return(np.unique(np.argwhere(M==28)[:,1]))


In [ ]:

# Ce bloc permet de valider votre code. Vous devez l'exécuter mais ne pas le modifier.  
try:
    M = np.array([[ 7, 21,  8, 12, 28, 20],
           [29, 28, 28,  9, 27, 16],
           [29,  7, 28,  7, 27, 26],
           [10, 10,  8, 22, 26, 12],
           [33, 22, 28,  5, 26, 18],
           [14, 28, 34,  9, 31, 26],
           [ 4, 15, 32, 23,  4, 34],
           [20, 20, 17, 19, 31,  8],
           [20,  5,  3, 27, 25, 24]])
    res = fct(M)
    np.testing.assert_equal(len(res),3,'Taille du vecteur incorrect.')
    np.testing.assert_equal(res,np.array([1, 2, 4]),'Exemple incorrect.')
    
except Exception as e: 
    print("\033[91m {}\033[00m" .format('KO - Au moins un test n\'est pas validé')) 
    print('Information sur le test non valide:')
    print(e)
    raise e
else:
    print("\033[92m {}\033[00m" .format('Ok - Tous les tests sont validés.')) 


 Ok - Tous les tests sont validés.
